import { NextResponse } from 'next/server';

// Curated major Asian city tourism + landmark webcams
// Sources: EarthCam public embeds, Skyline city pages, Windy city feeds
// Extended with traffic cam context where official feeds exist

export async function GET() {
  const cams = [
    // 🇯🇵 Japan
    { id: 'asia-tokyo-shibuya',      title: 'Shibuya Crossing, Tokyo',         lat: 35.6595,  lon: 139.7005, country: 'JP', city: 'Tokyo',         imageUrl: 'https://images.earthcam.com/ec_metros/ourcams/shibuya.jpg',       sourceUrl: 'https://www.earthcam.com/world/japan/tokyo/?cam=shibuya',                             sourceCountry: 'JP' },
    { id: 'asia-tokyo-shinjuku',     title: 'Shinjuku, Tokyo',                 lat: 35.6897,  lon: 139.7007, country: 'JP', city: 'Tokyo',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/japan/tokyo/shinjuku.html',                  sourceCountry: 'JP' },
    { id: 'asia-osaka-dotombori',    title: 'Dotonbori Canal, Osaka',          lat: 34.6687,  lon: 135.5019, country: 'JP', city: 'Osaka',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/japan.html',                                 sourceCountry: 'JP' },
    { id: 'asia-kyoto-gion',         title: 'Gion District, Kyoto',            lat: 35.0031,  lon: 135.7750, country: 'JP', city: 'Kyoto',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/japan.html',                                 sourceCountry: 'JP' },
    { id: 'asia-tokyo-bay',          title: 'Tokyo Bay / Rainbow Bridge',      lat: 35.6197,  lon: 139.7770, country: 'JP', city: 'Tokyo',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/japan.html',                                 sourceCountry: 'JP' },
    // 🇰🇷 South Korea
    { id: 'asia-seoul-hanriver',     title: 'Han River, Seoul',                lat: 37.5283,  lon: 126.9326, country: 'KR', city: 'Seoul',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/south-korea.html',                          sourceCountry: 'KR' },
    { id: 'asia-seoul-namsan',       title: 'N Seoul Tower / Namsan',          lat: 37.5512,  lon: 126.9882, country: 'KR', city: 'Seoul',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/south-korea.html',                          sourceCountry: 'KR' },
    { id: 'asia-busan-haeundae',     title: 'Haeundae Beach, Busan',           lat: 35.1587,  lon: 129.1604, country: 'KR', city: 'Busan',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/south-korea.html',                          sourceCountry: 'KR' },
    // 🇭🇰 Hong Kong
    { id: 'asia-hk-victoria',        title: 'Victoria Harbour, Hong Kong',     lat: 22.2855,  lon: 114.1577, country: 'HK', city: 'Hong Kong',     imageUrl: 'https://images.earthcam.com/ec_metros/ourcams/hongkong.jpg',       sourceUrl: 'https://www.earthcam.com/world/hongkong/?cam=hongkong',                              sourceCountry: 'HK' },
    { id: 'asia-hk-peak',            title: 'Victoria Peak, Hong Kong',        lat: 22.2716,  lon: 114.1453, country: 'HK', city: 'Hong Kong',     imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/hong-kong.html',                            sourceCountry: 'HK' },
    { id: 'asia-hk-tsim',            title: 'Tsim Sha Tsui, Kowloon',          lat: 22.2988,  lon: 114.1722, country: 'HK', city: 'Hong Kong',     imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/hong-kong.html',                            sourceCountry: 'HK' },
    // 🇹🇭 Thailand
    { id: 'asia-bangkok-center',     title: 'Central Bangkok (Silom)',         lat: 13.7235,  lon: 100.5291, country: 'TH', city: 'Bangkok',       imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/thailand.html',                             sourceCountry: 'TH' },
    { id: 'asia-bangkok-khao-san',   title: 'Khao San Road, Bangkok',          lat: 13.7589,  lon: 100.4977, country: 'TH', city: 'Bangkok',       imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/thailand.html',                             sourceCountry: 'TH' },
    { id: 'asia-phuket-patong',      title: 'Patong Beach, Phuket',            lat: 7.8964,   lon: 98.2960,  country: 'TH', city: 'Phuket',        imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/thailand/phuket/patong-beach.html',         sourceCountry: 'TH' },
    { id: 'asia-chiangmai-old',      title: 'Old City, Chiang Mai',            lat: 18.7883,  lon: 98.9853,  country: 'TH', city: 'Chiang Mai',    imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/thailand.html',                             sourceCountry: 'TH' },
    // 🇸🇬 Singapore
    { id: 'asia-sg-marina-bay',      title: 'Marina Bay Sands, Singapore',     lat: 1.2834,   lon: 103.8607, country: 'SG', city: 'Singapore',     imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/singapore.html',                            sourceCountry: 'SG' },
    { id: 'asia-sg-gardens',         title: 'Gardens by the Bay, Singapore',   lat: 1.2816,   lon: 103.8636, country: 'SG', city: 'Singapore',     imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/singapore.html',                            sourceCountry: 'SG' },
    { id: 'asia-sg-orchard',         title: 'Orchard Road, Singapore',         lat: 1.3047,   lon: 103.8321, country: 'SG', city: 'Singapore',     imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/singapore.html',                            sourceCountry: 'SG' },
    // 🇦🇪 UAE / Dubai
    { id: 'asia-dubai-marina',       title: 'Dubai Marina',                    lat: 25.0800,  lon: 55.1403,  country: 'AE', city: 'Dubai',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/united-arab-emirates/dubai/dubai-marina.html', sourceCountry: 'AE' },
    { id: 'asia-dubai-burj',         title: 'Burj Khalifa / Downtown Dubai',   lat: 25.1972,  lon: 55.2744,  country: 'AE', city: 'Dubai',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/united-arab-emirates.html',                 sourceCountry: 'AE' },
    { id: 'asia-dubai-palm',         title: 'Palm Jumeirah, Dubai',            lat: 25.1124,  lon: 55.1390,  country: 'AE', city: 'Dubai',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/united-arab-emirates.html',                 sourceCountry: 'AE' },
    { id: 'asia-abudhabi-corniche',  title: 'Abu Dhabi Corniche',              lat: 24.4765,  lon: 54.3705,  country: 'AE', city: 'Abu Dhabi',     imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/united-arab-emirates.html',                 sourceCountry: 'AE' },
    // 🇹🇼 Taiwan
    { id: 'asia-taipei-101',         title: 'Taipei 101 District',             lat: 25.0339,  lon: 121.5645, country: 'TW', city: 'Taipei',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/taiwan.html',                               sourceCountry: 'TW' },
    { id: 'asia-taipei-ximen',       title: 'Ximending, Taipei',               lat: 25.0424,  lon: 121.5080, country: 'TW', city: 'Taipei',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/taiwan.html',                               sourceCountry: 'TW' },
    // 🇲🇾 Malaysia
    { id: 'asia-kl-petronas',        title: 'Petronas Towers, KL',             lat: 3.1579,   lon: 101.7116, country: 'MY', city: 'Kuala Lumpur',   imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/malaysia.html',                             sourceCountry: 'MY' },
    { id: 'asia-kl-bukit-bintang',   title: 'Bukit Bintang, KL',               lat: 3.1453,   lon: 101.7130, country: 'MY', city: 'Kuala Lumpur',   imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/malaysia.html',                             sourceCountry: 'MY' },
    { id: 'asia-penang-ghtown',      title: 'George Town, Penang',             lat: 5.4141,   lon: 100.3288, country: 'MY', city: 'Penang',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/malaysia.html',                             sourceCountry: 'MY' },
    // 🇮🇩 Indonesia
    { id: 'asia-bali-kuta',          title: 'Kuta Beach, Bali',                lat: -8.7177,  lon: 115.1682, country: 'ID', city: 'Bali',           imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/indonesia.html',                            sourceCountry: 'ID' },
    { id: 'asia-bali-seminyak',      title: 'Seminyak Beach, Bali',            lat: -8.6912,  lon: 115.1603, country: 'ID', city: 'Bali',           imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/indonesia.html',                            sourceCountry: 'ID' },
    { id: 'asia-jakarta-center',     title: 'Central Jakarta',                 lat: -6.2088,  lon: 106.8456, country: 'ID', city: 'Jakarta',        imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/indonesia.html',                            sourceCountry: 'ID' },
    // 🇻🇳 Vietnam
    { id: 'asia-hanoi-hoan-kiem',    title: 'Hoan Kiem Lake, Hanoi',           lat: 21.0285,  lon: 105.8542, country: 'VN', city: 'Hanoi',          imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/vietnam.html',                              sourceCountry: 'VN' },
    { id: 'asia-hcmc-center',        title: 'Ho Chi Minh City Center',         lat: 10.7769,  lon: 106.7009, country: 'VN', city: 'Ho Chi Minh City', imageUrl: '',                                                              sourceUrl: 'https://www.skylinewebcams.com/en/webcam/vietnam.html',                              sourceCountry: 'VN' },
    // 🇵🇭 Philippines
    { id: 'asia-manila-bay',         title: 'Manila Bay',                      lat: 14.5794,  lon: 120.9780, country: 'PH', city: 'Manila',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/philippines.html',                          sourceCountry: 'PH' },
    { id: 'asia-boracay-beach',      title: 'Boracay White Beach',             lat: 11.9674,  lon: 121.9248, country: 'PH', city: 'Boracay',        imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/philippines.html',                          sourceCountry: 'PH' },
    // 🇮🇳 India
    { id: 'asia-mumbai-marine',      title: 'Marine Drive, Mumbai',            lat: 18.9438,  lon: 72.8234,  country: 'IN', city: 'Mumbai',         imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/india.html',                                sourceCountry: 'IN' },
    { id: 'asia-delhi-india-gate',   title: 'India Gate, New Delhi',           lat: 28.6129,  lon: 77.2295,  country: 'IN', city: 'New Delhi',      imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/india.html',                                sourceCountry: 'IN' },
    { id: 'asia-goa-calangute',      title: 'Calangute Beach, Goa',            lat: 15.5535,  lon: 73.7636,  country: 'IN', city: 'Goa',            imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/india.html',                                sourceCountry: 'IN' },
    // 🇨🇳 China
    { id: 'asia-shanghai-bund',      title: 'The Bund, Shanghai',              lat: 31.2397,  lon: 121.4905, country: 'CN', city: 'Shanghai',       imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/china.html',                                sourceCountry: 'CN' },
    { id: 'asia-beijing-tiananmen',  title: 'Tiananmen Square, Beijing',       lat: 39.9054,  lon: 116.3976, country: 'CN', city: 'Beijing',        imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/china.html',                                sourceCountry: 'CN' },
    { id: 'asia-guangzhou-center',   title: 'Pearl River, Guangzhou',          lat: 23.1291,  lon: 113.2644, country: 'CN', city: 'Guangzhou',      imageUrl: '',                                                                sourceUrl: 'https://www.skylinewebcams.com/en/webcam/china.html',                                sourceCountry: 'CN' },
  ];

  return NextResponse.json(cams, { status: 200 });
}
